[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "auto"
showErrorDetails = true

[runner]
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s" 